"""Module extension for Helm charts and toolchain."""

load(":versions.bzl", "DEFAULT_HELM_VERSION", "HELM_VERSIONS", "get_helm_url")

_KNOWN_WWW_AUTHENTICATE_CHALLENGES = {
    "ghcr.io": 'Bearer realm="https://ghcr.io/token",service="ghcr.io"',
}

_DOWNLOAD_HEADERS = {
    "Accept": ",".join([
        "application/vnd.docker.distribution.manifest.list.v2+json",
        "application/vnd.oci.image.index.v1+json",
        "application/vnd.docker.distribution.manifest.v2+json",
        "application/vnd.oci.image.manifest.v1+json",
    ]),
    "Docker-Distribution-API-Version": "registry/2.0",
}

def _merge_headers(primary, secondary):
    merged = {}
    for k, v in secondary.items():
        merged[k] = v
    for k, v in primary.items():
        merged[k] = v
    return merged

def _detect_platform(ctx):
    """Detect the host platform for binary download."""
    os = ctx.os.name
    arch = ctx.os.arch

    if os == "mac os x" or os.startswith("darwin"):
        os_name = "darwin"
    elif os.startswith("linux"):
        os_name = "linux"
    elif os.startswith("windows"):
        os_name = "windows"
    else:
        fail("Unsupported OS: {}".format(os))

    if arch == "amd64" or arch == "x86_64":
        arch_name = "amd64"
    elif arch == "aarch64" or arch == "arm64":
        arch_name = "arm64"
    else:
        fail("Unsupported architecture: {}".format(arch))

    return "{}_{}".format(os_name, arch_name)

def _get_exec_constraints(platform):
    """Get exec constraints for a platform."""
    parts = platform.split("_")
    os_constraint = {"darwin": "@platforms//os:macos", "linux": "@platforms//os:linux", "windows": "@platforms//os:windows"}[parts[0]]
    arch_constraint = {"amd64": "@platforms//cpu:x86_64", "arm64": "@platforms//cpu:aarch64"}[parts[1]]
    return [os_constraint, arch_constraint]

def _helm_toolchain_repo_impl(ctx):
    """Download helm binary and create toolchain."""
    platform = _detect_platform(ctx)
    version = ctx.attr.version
    key = "{}-{}".format(version, platform)

    if key not in HELM_VERSIONS:
        fail("Unsupported helm version/platform: {}".format(key))

    filename, sha256 = HELM_VERSIONS[key]
    url = get_helm_url(version, filename)

    # Helm tarballs have a directory structure like: {os}-{arch}/helm
    os_arch = platform.replace("_", "-")
    ctx.download_and_extract(url = url, sha256 = sha256, stripPrefix = os_arch)

    binary_name = "helm.exe" if platform.startswith("windows") else "helm"

    ctx.file("BUILD.bazel", """
package(default_visibility = ["//visibility:public"])

load("@helm.bzl//toolchain:toolchain.bzl", "helm_toolchain")

exports_files(["{binary}"])

helm_toolchain(
    name = "toolchain",
    helm = ":{binary}",
)

toolchain(
    name = "helm_toolchain",
    exec_compatible_with = {constraints},
    toolchain = ":toolchain",
    toolchain_type = "@helm.bzl//:toolchain_type",
)
""".format(binary = binary_name, constraints = _get_exec_constraints(platform)))

_helm_toolchain_repo = repository_rule(
    implementation = _helm_toolchain_repo_impl,
    attrs = {"version": attr.string(default = DEFAULT_HELM_VERSION)},
)

def _helm_chart_repo_impl(ctx):
    """Repository rule that downloads and extracts a Helm chart.

    Downloads the chart tarball from {repo_url}/{chart}-{version}.tgz,
    verifies SHA256, extracts it, and generates a BUILD.bazel exposing
    the chart files as a filegroup.

    Args:
        ctx: Repository rule context with chart, version, repo_url, and digest attrs.
    """
    chart_name = ctx.attr.chart
    version = ctx.attr.version
    repo_url = ctx.attr.repo_url
    digest = ctx.attr.digest

    # Construct chart URL: {repo_url}/{chart}-{version}.tgz
    chart_url = "{}/{}-{}.tgz".format(repo_url, chart_name, version)

    # Download and extract the chart tarball
    # TODO(bazel 9.0.1): revert to ctx.download_and_extract() once
    # bazelbuild/bazel#28454 (COMPRESS-705) is fixed in a release.
    ctx.download(
        url = chart_url,
        output = "chart.tgz",
        sha256 = _normalize_digest(digest),
    )
    res = ctx.execute(["tar", "xzf", "chart.tgz", "--strip-components=1"])
    if res.return_code != 0:
        fail("Failed to extract chart {}: {}".format(chart_name, res.stderr))
    ctx.delete("chart.tgz")

    # Generate BUILD.bazel exposing the chart files
    # Exclude BUILD.bazel itself and any Bazel-generated files from the glob
    ctx.file("BUILD.bazel", """\
# Auto-generated by helm.bzl module extension
# Chart: {chart} version {version}
# Source: {url}

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "chart",
    srcs = glob(
        ["**"],
        exclude = ["BUILD.bazel", "BUILD", "WORKSPACE", "WORKSPACE.bazel"],
    ),
)

# Convenience alias so `@repo` works in `bazel fetch @repo`.
alias(
    name = "{alias_name}",
    actual = ":chart",
    visibility = ["//visibility:public"],
)

# Expose Chart.yaml for metadata access
exports_files(["Chart.yaml", "values.yaml"])
""".format(
        chart = chart_name,
        version = version,
        url = chart_url,
        alias_name = ctx.attr.alias_name,
    ))

_helm_chart_repo = repository_rule(
    implementation = _helm_chart_repo_impl,
    attrs = {
        "chart": attr.string(
            mandatory = True,
            doc = "The name of the Helm chart (e.g., 'kratos')",
        ),
        "version": attr.string(
            mandatory = True,
            doc = "The version of the chart to download (e.g., '0.47.0')",
        ),
        "repo_url": attr.string(
            mandatory = True,
            doc = "The base URL of the Helm repository",
        ),
        "digest": attr.string(
            mandatory = True,
            doc = "Digest of the chart tarball (sha256:<hex>)",
        ),
        "alias_name": attr.string(
            mandatory = True,
            doc = "Alias target name for `bazel fetch @name` compatibility",
        ),
    },
    doc = "Downloads a Helm chart and exposes it as a filegroup.",
)

def _parse_www_authenticate(challenge):
    """Parse a WWW-Authenticate challenge string."""
    parts = challenge.split(" ", 1)
    if len(parts) != 2:
        return {}
    params = {}
    for item in parts[1].split(","):
        item = item.strip()
        if not item or "=" not in item:
            continue
        key, value = item.split("=", 1)
        value = value.strip()
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        params[key] = value
    return params

def _get_token_url(registry, repository, www_authenticate_challenges):
    challenge = None
    if www_authenticate_challenges and registry in www_authenticate_challenges:
        challenge = www_authenticate_challenges[registry]
    elif registry in _KNOWN_WWW_AUTHENTICATE_CHALLENGES:
        challenge = _KNOWN_WWW_AUTHENTICATE_CHALLENGES[registry]

    if not challenge:
        return None

    params = _parse_www_authenticate(challenge)
    realm = params.get("realm")
    if not realm:
        fail("WWW-Authenticate challenge for '{}' missing realm".format(registry))
    service = params.get("service", registry)
    scope = params.get("scope")
    if not scope:
        scope = "repository:{}:pull".format(repository)
    return "{}?service={}&scope={}".format(realm, service, scope)

def _download_registry_token(ctx, registry, repository, www_authenticate_challenges):
    token_url = _get_token_url(registry, repository, www_authenticate_challenges)
    if not token_url:
        return None
    ctx.download(
        url = token_url,
        output = "token.json",
        headers = _DOWNLOAD_HEADERS,
    )
    token_json = ctx.read("token.json")
    token = None
    for key in ["token", "access_token"]:
        key_idx = token_json.find('"' + key + '"')
        if key_idx == -1:
            continue
        colon_idx = token_json.find(":", key_idx)
        if colon_idx == -1:
            continue
        start_idx = token_json.find('"', colon_idx)
        if start_idx == -1:
            continue
        end_idx = token_json.find('"', start_idx + 1)
        if end_idx == -1:
            continue
        token = token_json[start_idx + 1:end_idx]
        break
    if not token:
        fail("Token response missing token field for registry '{}'".format(registry))
    return token

def _normalize_digest(value):
    if not value.startswith("sha256:"):
        fail("digest must be in the form 'sha256:<hex>' (got '{}')".format(value))
    digest = value[len("sha256:"):]
    if not digest:
        fail("digest must be in the form 'sha256:<hex>' (got '{}')".format(value))
    for i in range(len(digest)):
        ch = digest[i]
        if not ((ch >= "0" and ch <= "9") or (ch >= "a" and ch <= "f")):
            fail("digest must be lowercase hex in the form 'sha256:<hex>' (got '{}')".format(value))
    return digest

def _helm_oci_chart_repo_impl(ctx):
    """Download a Helm chart from an OCI registry using Bazel's downloader."""
    registry = ctx.attr.registry
    repository = ctx.attr.repository
    chart_name = ctx.attr.chart
    version = ctx.attr.version
    digest = ctx.attr.digest

    if repository.startswith("oci://"):
        repository = repository[len("oci://"):]

    if repository.startswith(registry + "/"):
        repository = repository[len(registry) + 1:]

    sha256_clean = _normalize_digest(digest)

    token = _download_registry_token(
        ctx,
        registry = registry,
        repository = repository,
        www_authenticate_challenges = ctx.attr.www_authenticate_challenges,
    )
    headers = {}
    if token:
        headers["Authorization"] = "Bearer " + token

    blob_url = "https://{registry}/v2/{repository}/blobs/{digest}".format(
        registry = registry,
        repository = repository,
        digest = digest,
    )

    ctx.download(
        url = blob_url,
        output = "chart.tgz",
        sha256 = sha256_clean,
        headers = _merge_headers(headers, _DOWNLOAD_HEADERS),
    )

    # TODO(bazel 9.0.1): revert to ctx.extract() once
    # bazelbuild/bazel#28454 (COMPRESS-705) is fixed in a release.
    res = ctx.execute(["tar", "xzf", "chart.tgz", "--strip-components=1"])
    if res.return_code != 0:
        fail("Failed to extract OCI chart {}: {}".format(chart_name, res.stderr))
    ctx.delete("chart.tgz")

    ctx.file("BUILD.bazel", """\
# Auto-generated by helm.bzl module extension
# Chart: {chart} version {version}
# Source: oci://{registry}/{repository}@{digest}

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "chart",
    srcs = glob(
        ["**"],
        exclude = ["BUILD.bazel", "BUILD", "WORKSPACE", "WORKSPACE.bazel"],
    ),
)

# Convenience alias so `@repo` works in `bazel fetch @repo`.
alias(
    name = "{alias_name}",
    actual = ":chart",
    visibility = ["//visibility:public"],
)

# Expose Chart.yaml for metadata access
exports_files(["Chart.yaml", "values.yaml"])
""".format(
        chart = chart_name,
        version = version,
        registry = registry,
        repository = repository,
        digest = digest,
        alias_name = ctx.attr.alias_name,
    ))

_helm_oci_chart_repo = repository_rule(
    implementation = _helm_oci_chart_repo_impl,
    attrs = {
        "registry": attr.string(
            mandatory = True,
            doc = "Registry hostname (e.g., 'ghcr.io')",
        ),
        "repository": attr.string(
            mandatory = True,
            doc = "Repository path beneath the registry (e.g., 'org/charts/chart')",
        ),
        "chart": attr.string(
            mandatory = True,
            doc = "Helm chart name (used for stripPrefix)",
        ),
        "version": attr.string(
            mandatory = True,
            doc = "Chart version tag (for documentation)",
        ),
        "digest": attr.string(
            mandatory = True,
            doc = "Digest of the chart layer blob (sha256:<hex>)",
        ),
        "www_authenticate_challenges": attr.string_dict(
            doc = "Map of registry hostnames to WWW-Authenticate challenges.",
        ),
        "alias_name": attr.string(
            mandatory = True,
            doc = "Alias target name for `bazel fetch @name` compatibility",
        ),
    },
    doc = "Downloads a Helm chart from an OCI registry and exposes it as a filegroup.",
)

def _helm_extension_impl(ctx):
    """Module extension implementation for Helm charts and toolchain.

    Collects all repo and chart tags from modules, validates that charts
    reference valid repos, and creates repository rules for each chart.
    Also creates the helm toolchain if requested.
    """

    # Process toolchain tags
    for mod in ctx.modules:
        for toolchain in mod.tags.toolchain:
            _helm_toolchain_repo(
                name = "helm_toolchains",
                version = toolchain.version or DEFAULT_HELM_VERSION,
            )

    # Collect all repos first (keyed by name)
    repos = {}
    for mod in ctx.modules:
        for repo in mod.tags.repo:
            if repo.name in repos:
                # Allow duplicate repos if they have the same URL
                if repos[repo.name] != repo.url:
                    fail("Duplicate Helm repo '{}' with different URLs: '{}' vs '{}'".format(
                        repo.name,
                        repos[repo.name],
                        repo.url,
                    ))
            repos[repo.name] = repo.url

    # Process all chart tags and create repository rules
    for mod in ctx.modules:
        for chart in mod.tags.chart:
            # Validate that the chart references a known repo
            if chart.repo not in repos:
                fail("Chart '{}' references unknown repo '{}'. Available repos: {}".format(
                    chart.name,
                    chart.repo,
                    ", ".join(repos.keys()) if repos else "(none)",
                ))

            # Create the repository rule for this chart
            _helm_chart_repo(
                name = chart.name,
                chart = chart.chart,
                version = chart.version,
                repo_url = repos[chart.repo],
                digest = chart.digest,
                alias_name = chart.name,
            )
        for chart in mod.tags.oci_chart:
            _helm_oci_chart_repo(
                name = chart.name,
                registry = chart.registry,
                repository = chart.repository,
                chart = chart.chart,
                version = chart.version,
                digest = chart.digest,
                www_authenticate_challenges = chart.www_authenticate_challenges,
                alias_name = chart.name,
            )

# Tag class for declaring Helm toolchain
_toolchain_tag = tag_class(
    attrs = {
        "version": attr.string(
            doc = "Helm version to use (default: {})".format(DEFAULT_HELM_VERSION),
        ),
    },
    doc = "Configures the Helm toolchain.",
)

# Tag class for declaring a Helm repository
_repo_tag = tag_class(
    attrs = {
        "name": attr.string(
            mandatory = True,
            doc = "Name to reference this repo (e.g., 'ory')",
        ),
        "url": attr.string(
            mandatory = True,
            doc = "Base URL of the Helm repository (e.g., 'https://k8s.ory.sh/helm/charts')",
        ),
    },
    doc = "Declares a Helm chart repository.",
)

# Tag class for declaring a Helm chart to download
_chart_tag = tag_class(
    attrs = {
        "repo": attr.string(
            mandatory = True,
            doc = "Name of the repo declared with helm.repo()",
        ),
        "chart": attr.string(
            mandatory = True,
            doc = "Helm chart name as it appears in the repository",
        ),
        "name": attr.string(
            mandatory = True,
            doc = "Bazel repository name (will be available as @name)",
        ),
        "version": attr.string(
            mandatory = True,
            doc = "Chart version to download",
        ),
        "digest": attr.string(
            mandatory = True,
            doc = "Digest of the chart tarball (sha256:<hex>)",
        ),
    },
    doc = "Declares a Helm chart to download from a repository.",
)

_oci_chart_tag = tag_class(
    attrs = {
        "registry": attr.string(
            mandatory = True,
            doc = "Registry hostname (e.g., 'ghcr.io')",
        ),
        "repository": attr.string(
            mandatory = True,
            doc = "Repository path beneath the registry (e.g., 'org/charts/chart')",
        ),
        "chart": attr.string(
            mandatory = True,
            doc = "Helm chart name as it appears in the repository",
        ),
        "name": attr.string(
            mandatory = True,
            doc = "Bazel repository name (will be available as @name)",
        ),
        "version": attr.string(
            mandatory = True,
            doc = "Chart version tag",
        ),
        "digest": attr.string(
            mandatory = True,
            doc = "Digest of the chart layer blob (sha256:<hex>)",
        ),
        "www_authenticate_challenges": attr.string_dict(
            doc = "Map of registry hostnames to WWW-Authenticate challenges.",
        ),
    },
    doc = "Declares a Helm chart to download from an OCI registry.",
)

helm = module_extension(
    implementation = _helm_extension_impl,
    tag_classes = {
        "toolchain": _toolchain_tag,
        "repo": _repo_tag,
        "chart": _chart_tag,
        "oci_chart": _oci_chart_tag,
    },
    doc = "Module extension for Helm toolchain and charts.",
)
